### ISSUE TITLE
QA - Certain domain names cause UnboundLocalError

### ISSUE THREAD

**Issue by infamousjoeg** [infamousjoeg/DNAmicAnalysis#55]
```shell
$ ./DNAmicAnalysis.py data/DNA_2019-08-07_19-45-46-PM.db -d napa.ad.etn.com -s "svc, service" -a "admin" -t
Traceback (most recent call last):
  File "./DNAmicAnalysis.py", line 471, in <module>
    main(args)
  File "./DNAmicAnalysis.py", line 48, in main
    domain_names = db.exec_fromfile("data/sql/ADDomainCheck.sql")
  File "/Users/joegarcia/Git/infamousjoeg/DNAmicAnalysis/dnamic_analysis/database.py", line 90, in exec_fromfile
    c.execute(sqlQueryFinal)
UnboundLocalError: local variable 'sqlQueryFinal' referenced before assignment
```

**Comment by infamousjoeg** [comment]
The DNA database file is in the wrong format -- should be 12-hour format for time in datetime stamp, not 24-hour format.  Changing and running tests.

**Comment by infamousjoeg** [comment]
Tested successfully:

```shell
╰ ./DNAmicAnalysis.py data/DNA_2019-08-07_07-45-46-PM.db -d napa.ad.etn.com -s "svc, service" -a "admin" -t
====================================================
Found napa.ad.etn.com out of 10 total domains
in the provided DNA scan database.
----------------------------------------------------
Domains found:
napa.ad.etn.com
ad.etn.com
eaton.ad.etn.com
nasa.ad.etn.com
euro.ad.etn.com
easohsvtfs04
easohsvtfs03
napa
eaton
nasa
----------------------------------------------------
Press ENTER to continue...
====================================================
```
